- hosts: all
  become: true
  roles:
   - role: commons

- hosts: grupo_sw
  become: true
  roles:
   - role: nginx
  
- hosts: grupo_sw
  become: true
  roles:
   - role: mariadb

- hosts: grupo_sw
  become: true
  roles:
   - role: php-fpm
