- name: Install nginx
  apt:
    pkg: nginx
  
- name: Configuración de virtualhost
  template: 
    src: etc/nginx/sites-available/vhost.j2
    dest: /etc/nginx/sites-available/{{item["name"]}}
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{virtualhosts}}"

- name: Create documentroot if it does not exist
  ansible.builtin.file:
    path: /{{item["datos"]["documentroot"]}}
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  with_items:
    - "{{virtualhosts}}"


- name: Add vhost symlink in sites-enabled.
  file:
    src: /etc/nginx/sites-available/{{item["name"]}}
    dest: /etc/nginx/sites-enabled/{{item["name"]}}
    state: link
    mode: 0755
  with_items:
    - "{{virtualhosts}}"
  notify: restart nginx
  

- name: Copy index.html
  copy:
    src: index_{{item["name"]}}.html
    dest: /{{item["datos"]["documentroot"]}}/index.html
    owner: www-data
    group: www-data
    mode: 0644
  with_items:
    - "{{virtualhosts}}"

- name: Activar virtualhost
  file:
    src: /etc/nginx/sites-available/vhost.j2
    dest: /etc/nginx/sites-enabled/vhost.j2
    state: link
    mode: 0755
  notify: restart nginx

- name: Delete virtualhosts
  file:
    dest: /etc/nginx/sites-enabled/{{item["name"]}}
    state: absent
  with_items:
    - "{{virtualhosts2}}"
  notify: restart nginx
